---

- name: Provisioning application
  hosts: '{{instance}}'
  gather_facts: no
  sudo: yes
  sudo_user: ubuntu
  remote_user: ubuntu

  vars:
    - virtualenv_path: '{{virtualenv}}'
    - django_dir: '{{django_dir}}'
    - requirements_file: '{{django_requirements}}'
    - django_settings_file: '{{django_dir}}'
    - django_secret_key: '{{django_secret_key}}'
    - run_django_syncdb: yes
    - run_django_migrations: yes
    - run_django_collectstatic: yes
    - setup_git_repo: yes
    - git_repo: '{{github_repo}}'
    - nginx_server_name: localhost
    - nginx_http_port: 80
    - nginx_https_port: 443

  vars_files:
    - ./vars/common.yml
    - ./vars/{{instance}}.yml

  roles:
    - python
    - postgres
    - webparticipation
    - ureport
    - redis
    - celery
    - nginx
