---

- name: Provisioning application
  hosts: ureport
  gather_facts: no
  sudo: yes
  sudo_user: ubuntu
  remote_user: ubuntu

  vars:
    - run_django_syncdb: yes
    - run_django_migrations: yes
    - run_django_collectstatic: yes
    - setup_git_repo: yes
    - nginx_server_name: localhost
    - nginx_http_port: 80
    - nginx_https_port: 443
    - nginx_site: ureport

  vars_files:
    - ./vars/common.yml
  roles:
    - python
    - supervisor
    - postgres
    - redis
    - ureport
    - nginx
