---

- name: Pull latest ureport application code from github
  sudo_user: root
  git: repo={{ureport_git_repo}} dest={{ureport_repo}} update=yes accept_hostkey=yes
  notify: reload ureport
  tags: 
    - git 
