---

- name: Include default step variables
  include_vars: ../../../vars/{{instance}}.yml

- name: Create log directory for celery
  sudo: yes
  sudo_user: root
  file: path=/var/log/celery
    owner={{remote_user}}
    group={{remote_user}}
    state=directory
  tags: celery

- name: Generate configuration file for supervisor
  sudo_user: root
  template: src=supervisor_celery_conf.j2
            dest=/etc/supervisor/conf.d/celery.conf
            backup=yes

- name: Ensure Supervisor service is started
  service: name=supervisor state=started enabled=yes

- name: Re-read the Supervisor config files
  remote_user: ubuntu
  sudo_user: root
  sudo: yes
  command: supervisorctl reread

- name: Update Supervisor config
  remote_user: ubuntu
  sudo_user: root
  sudo: yes
  command: supervisorctl update
