---

- name: Include default step variables
  include_vars: ../../../vars/{{instance}}.yml

- name: Create log directory for celery
  sudo: yes
  sudo_user: root
  file: path=/var/log/celery
    owner={{remote_user}}
    group={{remote_user}}
    state=directory
  tags: celery

- name: Generate configuration file for supervisor
  sudo_user: root
  notify: restart webparticipation-celery
  template: src=supervisor_celery_conf.j2
            dest=/etc/supervisor/conf.d/celery.conf
            backup=yes
