---
- name: include default step variables
  include_vars: ../../vars/main.yml

- name: Ensure that redis server is installed
  sudo_user: root
  apt: name=redis-server update_cache=yes state=installed
  tags: redis

- name: Switch to using upstart
  template: src=redis_conf.j2 dest="/etc/init/redis-server.conf" 
  tags: redis

- name: Append 'daemonizie=no' to config 
  lineinfile: >
    dest='/etc/redis/redis.conf'
    line='daemonize no'
    insertafter=EOF
    backup='yes'
  tags: redis

- name: Create log directory for celery
  file: path={{project_dir}}/celery
    owner={{remote_user}}
    group={{remote_user}}
    state=directory
  tags: celery

- name: Initialise log rotation for Celery logs
  sudo_user: root
  template: src=celery_log.j2
    dest='/etc/logrotate.d/application_name.log'
    owner={{remote_user}}
    group={{remote_user}}
  tags: celery

- name: Re-read the Supervisor config files
  remote_user: root
  command: supervisorctl reread
  notify: restart webparticipation-celery
