---
- name: Include default step variables
  include_vars: ./vars.yml

- name: Install PostgreSQL
  sudo_user: root
  apt: name={{item}} update_cache=yes state=installed
  with_items:
    - postgresql-9.3
    - postgresql-contrib
    - libpq-dev
    - python-psycopg2
  tags: packages

- name: Ensure the PostgreSQL service is running
  sudo_user: root
  sudo: yes
  service: name=postgresql state=started enabled=yes

- name: Ensure database is created
  sudo_user: postgres
  sudo: yes
  postgresql_db: db={{database_name}} state=present

- name: Ensure user has access to the database
  sudo_user: postgres
  postgresql_user: db={{database_name}}
                   name={{database_user}}
                   password={{database_password}}
                   priv=ALL
                   state=present

- name: Ensure user does not have unnecessary privileges
  sudo_user: postgres
  sudo: yes
  postgresql_user: name={{database_user}}
                   role_attr_flags=SUPERUSER,CREATEDB,LOGIN
                   state=present

- name: Restart Postgresql
  sudo_user: postgres
  sudo: yes
  service: name=postgresql state=restarted enabled=yes

- name: Install Postgres client components
  sudo_user: root
  apt: name={{ item }} update_cache=yes state=installed
  with_items:
    - libpq-dev
    - python-psycopg2
  tags: packages
